language: objective-c
osx_image: xcode12
xcode_workspace: Passepartout.xcworkspace
xcode_scheme: PassepartoutCore-iOS
xcode_destination: platform=iOS Simulator,OS=12.4,name=iPhone Xs Max
cache:
    - bundler
    - cocoapods
install:
    - bundle install --jobs=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
    - bundle exec pod repo update
    - travis_wait 40 bundle exec pod install

branches:
    only:
        - master
